# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a010f6e26d009500d6457ace86fee9d7491c1432e59f227999fcafe924b1dd0f70d9e1d79c89dd1236ea9c2af3785344cbe21c35b8f78a7b71d9a988fad7240

test:
  secret_key_base: 5a65013bf29c2a60350f1caa259f81d65c4db983430d12e326d5d17009eda88c26813ee3f3253a5a89f68975aed688a481d1e7cd8241cab28c4e5272c66916b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
